apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::315069654700:role/eksctl-roboshop-cluster-nodegroup--NodeInstanceRole-yZS3T6m0Z2Am
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-pod-reader
      userarn: arn:aws:iam::315069654700:user/ramesh
      username: ramesh
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::315069654700:user/raheem
      username: raheem
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  uid: c545fed5-5d66-41bb-be7b-13e318a33fd2